name: Pre Merge Checks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  gradle:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, 'ci skip') }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Run build scripts
        run: |
          cd library-android/buildscripts
          ./download.sh
          ./build_python.sh

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Run Gradle
        env:
          ANDROID_HOME: 'library-android/buildscripts/sdk/android-sdk-linux'
          ANDROID_SDK_ROOT: 'library-android/buildscripts/sdk/android-sdk-linux'
        run: ./gradlew build check publishToMavenLocal --continue
