name: Publish release

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build the release artifacts
        run: |
          set -e
          cd library-android/buildscripts
          ./download.sh
          ./build_python.sh
          cd ../..
          ./gradlew library-android:build
      - name: Get tag name
        run: |
          set -x
          echo "VERSION_TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
      - name: Copy build artifacts
        run: |
          set -e
          mv library-android/build/outputs/aar/library-android-release.aar aniparse-android-${{ env.VERSION_TAG }}.aar
      - name: Create Release
        uses: softprops/action-gh-release@v0.1.15
        with:
          tag_name: ${{ env.VERSION_TAG }}
          name: aniparse-android ${{ env.VERSION_TAG }}
          body: |
            aniparse-android version ${{ env.VERSION_TAG }}
          files: |
            aniparse-android-${{ env.VERSION_TAG }}.aar
